
sever.port: 8081

spring:
  cloud:
    discovery:
      client:
        simple:
          instances:
            mqtt:
              - uri: tcp://localhost:1883
logging:
  level:
    org.eclipse.paho.client.mqttv3.internal.nls.logcat: info
