bridge:
  dmx-lights:
    - id: "l1"
      name: "1. OG, Büro, über Türe"
      dmxBricklet: EJy
      warmAddress: 0
      coldAddress: 1
      warmTemperature: 2700
      coldTemperature: 7500
sever.port: 8081

spring:
  cloud:
    discovery:
      client:
        simple:
          instances:
            mqtt:
              - uri: tcp://localhost:1883
            tf:
              - uri: tcp://10.192.64.11:4223
              - uri: tcp://10.192.64.15:4223
              - uri: tcp://10.192.64.23:4223
    kubernetes:
      config:
        enable-api: false
        enabled: false
      secrets:
        enabled: false
      discovery:
        enabled: false
logging:
  level:
    org.eclipse.paho.client.mqttv3.internal.nls.logcat: debug
